# Generated by Django 2.0 on 2017-10-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IkeaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('product_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('code', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('picture_url', models.URLField()),
                ('datetime', models.DateTimeField(verbose_name='date added')),
                ('status', models.CharField(choices=[('n', 'Новое'), ('a', 'Заказано'), ('d', 'Выполнено'), ('c', 'Отклонено')], max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikealist.Customer')),
            ],
        ),
    ]
