# Generated by Django 2.0 on 2017-10-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ikealist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikeaitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ikealist.Customer'),
        ),
    ]
